config/routes.rb
Rails.application.routes.draw do

	devise_for :users
	root to: "home#index"

	resource :contact, only: [:new, :create], path_names: {:new=>''}

	get 'home/index'

	get 'terms' => 'pages#terms'
	get 'about' => 'pages#about'

	resources :articles do
		resources :comments
	end

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true
	validates :text, presence: true
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :email, presence: true
	validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_filter :authenticate_user!

def new
	
end

def edit
	@article = Article.find(params[:id])
end

def update
	@article = Article.find(params[:id])
		if @article.update (article_params)
		redirect_to @article
	else
		render action: 'edit'
	end
end

def index
	@articles=Article.all
end

def show
	@article = Article.find(params[:id])
end

def create
	@article = Article.new(article_params)

	if @article.save
		redirect_to @article
	else
		render action: 'new'
	end
end

def destroy
	@article=Article.find(params[:id])
	@article.destroy
	redirect_to articles_path
end

private

	def article_params
		params.require(:article).permit(:text, :title)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article= Article.find(params[:article_id])
		@article.comments.create(comment_params)
		
		redirect_to article_path (@article)
	end
	
	private
	
	def comment_params
		params.require(:comment).permit(:author,:body)
	end
	
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
	
	end
	def create
		@contact= Contact.new(contact_params)
		#render plain: params[:contact].inspect
	
		if @contact.valid? 
		@contact.save 
		else
			render action: :new
		end
	end
	private

	def contact_params
		params.require(:contact).permit(:email, :message)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def terms
		
	end

	def about
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<%=form_for :article, url: article_path(@article), method: :put do |f|%>

	<%if @article && @article.errors.any?%>

		<p>
			<ul>
				<%@article.errors.full_messages.each do |m|%>
					<li><%=m%></li>
				<%end%>
			</ul>
		</p>

	<%end%>

	<p>
		<%=f.label :title%></br>
		<%=f.text_field :title%>
	</p>	
	<p>
		<%=f.label :text%></br>
		<%=f.text_area :text%>
	</p>
	<p>
		<%=f.submit%></br>
	</p>
<%end%>

app/views/articles/index.html.erb
<%@articles.each do |a|%>
<h2><%=a.title%></h2>
<p><%=a.text%></p>
<%=link_to "Show", article_path(a)%> |
<%=link_to "Edit", edit_article_path(a)%> |
<%=link_to "Delete", article_path(a), method: :delete, data: {confirm: "This will remove the data permanently! Do you want to proceed?"}%>
<hr>


<%end%>

app/views/articles/new.html.erb
<h1>
	New Article
</h1>
<%=form_for :article, url: articles_path do |f|%>

	<%if @article && @article.errors.any?%>

		<p>
			<ul>
				<%@article.errors.full_messages.each do |m|%>
					<li><%=m%></li>
				<%end%>
			</ul>
		</p>

	<%end%>

	<p>
		<%=f.label :title%></br>
		<%=f.text_field :title%>
	</p>	
	<p>
		<%=f.label :text%></br>
		<%=f.text_area :text%>
	</p>
	<p>
		<%=f.submit%></br>
	</p>
<%end%>

app/views/articles/show.html.erb
<h2>
<%=@article.title%>
</h2>
<p>
<%=@article.text%>
</p>
<hr>

<%@article.comments.each do |c|%>
<p style="font:75%"><b><%=c.author%></b> said at <%=c.created_at%>:</p>
<p><%=c.body%></p>
<hr>
<%end%>

<p>
<%= form_for([@article, @article.comments.build]) do |f| %>
		<p>
		<%=f.label :author%></br>
		<%=f.text_field :author%>
	</p>
	<p>
		<%=f.label :text%></br>
		<%=f.text_area :body%>
	</p>
	<p>
		<%=f.submit%></br>
	</p>
<%end%>
</p>

app/views/contacts/create.html.erb
<h1>Thank you!</h1>

<%=render plain: params[:contact].inspect%>

app/views/contacts/new.html.erb
<p>Find me in app/views/contact/new.html.erb</p>
<h1>Contact Us</h1>

<%=form_for :contact, url: contact_path do |f|%>
	<%if @contact && @contact.errors.any?%>

		<p>
			<ul>
				<%@contact.errors.full_messages.each do |m|%>
					<li><%=m%></li>
				<%end%>
			</ul>
		</p>

	<%end%>
	<p>
		<%=f.label :email%></br>
		<%=f.text_field :email%>
	</p>
	<p>
		<%=f.label :message%></br>
		<%=f.text_area :message%>
	</p>
	<p>
		<%=f.submit "Send Message" %></br>
	</p>
<%end%>

</form>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blog</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<a href="/users/sign_out" data-method="delete">Sign Out</a> | 
	<a href="/users/sign_in">Sign In</a>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h2>
About us
</h2>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dapibus rhoncus augue id bibendum. Nam leo est, posuere mollis elementum eu, egestas id nisi. Vestibulum quis hendrerit augue. Mauris lobortis eros ac ante sodales, vitae euismod nunc congue. Proin id ligula tincidunt, semper nibh id, semper arcu. Maecenas tempus egestas laoreet. Aliquam laoreet velit eget vehicula malesuada. Pellentesque at tortor sit amet tellus pharetra pellentesque. Fusce ultrices vel mauris eu pulvinar. Integer pharetra vestibulum pellentesque. Nullam sed tincidunt orci. Nullam quis nunc nisl. Duis ultrices at nisi at eleifend. In consequat dictum lobortis. Suspendisse non pellentesque neque, quis pharetra dolor. Duis ac finibus magna.

Nam at libero ex. Donec maximus, eros quis iaculis volutpat, leo odio commodo ex, in pellentesque elit sapien auctor metus. Fusce tempus ante et nisi scelerisque congue. Curabitur ut urna velit. Etiam sit amet tortor in tortor blandit vehicula ac non arcu. Nulla facilisi. Suspendisse luctus turpis ac justo feugiat efficitur. Duis imperdiet auctor nisl varius volutpat. Pellentesque maximus magna vitae sagittis bibendum.

Cras sagittis mollis justo et lacinia. Morbi eu erat in nisl commodo efficitur. Etiam sed ex id massa imperdiet consequat. Donec luctus odio dolor, ac vulputate urna blandit et. Nunc mattis malesuada congue. Nulla luctus libero ut arcu fermentum, vitae blandit eros feugiat. Donec rhoncus malesuada massa non dignissim. Phasellus ut bibendum ante, et laoreet neque. Duis viverra eros eu nunc vestibulum, sed condimentum justo vulputate. Integer facilisis tempor quam, vitae feugiat mauris cursus eget. Curabitur nec urna neque. Vivamus laoreet est eget semper fermentum.

Duis id aliquet elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi malesuada libero ac quam vulputate, vitae sodales ligula condimentum. Vivamus ut sapien sit amet tellus facilisis vulputate. Curabitur lectus diam, mattis quis lorem ac, bibendum sagittis nulla. Praesent sed varius mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac finibus diam. Nunc viverra turpis ut eros varius consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer blandit, arcu et pretium gravida, nisl nisl porta velit, ac volutpat mauris lectus a ipsum. Quisque finibus nisi rutrum, molestie ipsum commodo, placerat sapien. Morbi sit amet urna placerat, fringilla est vel, consectetur nisl.

Nunc odio est, lacinia quis tempor nec, dictum eget justo. Donec sapien urna, condimentum vitae volutpat nec, bibendum vitae sem. Pellentesque scelerisque aliquam mauris, sit amet posuere ipsum venenatis at. Mauris sapien enim, rhoncus interdum ligula at, vestibulum finibus mi. Nam mollis ipsum quam, ac ullamcorper velit hendrerit eget. Donec laoreet arcu sed felis ultrices commodo. Nam placerat mauris neque, convallis vehicula odio lobortis eu. Integer porta et purus at tempor. Mauris lacinia nisi vel risus finibus pulvinar. Sed at augue malesuada, iaculis velit vel, placerat ex. Morbi mollis purus at ex condimentum congue. 
</p>

app/views/pages/terms.html.erb
<h2>
Terms of Service
</h2>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dapibus rhoncus augue id bibendum. Nam leo est, posuere mollis elementum eu, egestas id nisi. Vestibulum quis hendrerit augue. Mauris lobortis eros ac ante sodales, vitae euismod nunc congue. Proin id ligula tincidunt, semper nibh id, semper arcu. Maecenas tempus egestas laoreet. Aliquam laoreet velit eget vehicula malesuada. Pellentesque at tortor sit amet tellus pharetra pellentesque. Fusce ultrices vel mauris eu pulvinar. Integer pharetra vestibulum pellentesque. Nullam sed tincidunt orci. Nullam quis nunc nisl. Duis ultrices at nisi at eleifend. In consequat dictum lobortis. Suspendisse non pellentesque neque, quis pharetra dolor. Duis ac finibus magna.

Nam at libero ex. Donec maximus, eros quis iaculis volutpat, leo odio commodo ex, in pellentesque elit sapien auctor metus. Fusce tempus ante et nisi scelerisque congue. Curabitur ut urna velit. Etiam sit amet tortor in tortor blandit vehicula ac non arcu. Nulla facilisi. Suspendisse luctus turpis ac justo feugiat efficitur. Duis imperdiet auctor nisl varius volutpat. Pellentesque maximus magna vitae sagittis bibendum.

Cras sagittis mollis justo et lacinia. Morbi eu erat in nisl commodo efficitur. Etiam sed ex id massa imperdiet consequat. Donec luctus odio dolor, ac vulputate urna blandit et. Nunc mattis malesuada congue. Nulla luctus libero ut arcu fermentum, vitae blandit eros feugiat. Donec rhoncus malesuada massa non dignissim. Phasellus ut bibendum ante, et laoreet neque. Duis viverra eros eu nunc vestibulum, sed condimentum justo vulputate. Integer facilisis tempor quam, vitae feugiat mauris cursus eget. Curabitur nec urna neque. Vivamus laoreet est eget semper fermentum.

Duis id aliquet elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi malesuada libero ac quam vulputate, vitae sodales ligula condimentum. Vivamus ut sapien sit amet tellus facilisis vulputate. Curabitur lectus diam, mattis quis lorem ac, bibendum sagittis nulla. Praesent sed varius mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ac finibus diam. Nunc viverra turpis ut eros varius consectetur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer blandit, arcu et pretium gravida, nisl nisl porta velit, ac volutpat mauris lectus a ipsum. Quisque finibus nisi rutrum, molestie ipsum commodo, placerat sapien. Morbi sit amet urna placerat, fringilla est vel, consectetur nisl.

Nunc odio est, lacinia quis tempor nec, dictum eget justo. Donec sapien urna, condimentum vitae volutpat nec, bibendum vitae sem. Pellentesque scelerisque aliquam mauris, sit amet posuere ipsum venenatis at. Mauris sapien enim, rhoncus interdum ligula at, vestibulum finibus mi. Nam mollis ipsum quam, ac ullamcorper velit hendrerit eget. Donec laoreet arcu sed felis ultrices commodo. Nam placerat mauris neque, convallis vehicula odio lobortis eu. Integer porta et purus at tempor. Mauris lacinia nisi vel risus finibus pulvinar. Sed at augue malesuada, iaculis velit vel, placerat ex. Morbi mollis purus at ex condimentum congue. 
</p>